### ISSUE TITLE
Fix Tandem Generation

### ISSUE THREAD

**Issue by michaelwkudla** [brachify/brachify#5]
Fundamentally, we need to refactor how the tandems are generated. It should be fairly easy to solve for the geometry so that there is limited opportunity for bugs. 
This includes limiting the resolution (maybe down to the nearest 0.1 degrees?)
Range of options from 0 degrees to 90 degrees.

**Comment by nsmela** [comment]
tandem rework ported over. Issue with channel cylinder for stopper when tandem angle between 1-15 degrees. Otherwise, tandem is more flexible than before.

Suspect issue is here:
https://github.com/brachify/brachify/blob/b567f9200be2ffa7eeac674a2bddae74a498bce9/src/classes/mesh/tandem.py#L94

Keep noted that with a large bending radius, the tandem could exit the cylinder and you couldn't tell if it's fully doing the job. A smaller bend radius will show up better.

**Comment by michaelwkudla** [comment]
This is largely resolved now. There are still probably some corner case issues, but we can deal with those over time.
